Repository BudgetBuddiesTeam/BackEnd, pull requests merged in 2024-09, with the labels that each got.

#180 [fix] 동일한 이름의 카테고리 생성 관련 이슈 해결
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/converter/CategoryConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
Labels: :hammer_and_wrench: fix

#183 Fix/#181 소비목표 조회 로직 변경
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/converter/CategoryConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
Labels: :hammer_and_wrench: fix

#186 [refactor] 소비 분석 레포트 평균치 조정
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#191 [feat] 엔티티 생성 및 수정
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/entity/Comment.java
  src/main/java/com/bbteam/budgetbuddies/domain/connectedinfo/entity/ConnectedInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/connectedinfo/repository/ConnectedInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/entity/Expense.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/entity/Faq.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/repository/FaqRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/favoritehashtag/entity/FavoriteHashtag.java
  src/main/java/com/bbteam/budgetbuddies/domain/favoritehashtag/repository/FavoriteHashtagRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/entity/Hashtag.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/notification/entity/Notification.java
  src/main/java/com/bbteam/budgetbuddies/domain/notification/repository/NotificationRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/entity/Report.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/repository/ReportRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/entity/User.java
  src/main/java/com/bbteam/budgetbuddies/enums/NotiType.java
  src/main/java/com/bbteam/budgetbuddies/enums/Role.java
Labels: :gear: feature

#190 [feat] Notice(공지사항) 관련 로직 추가
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/controller/NoticeApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/controller/NoticeController.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/converter/NoticeConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/dto/NoticeRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/dto/NoticeResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/entity/Notice.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/repository/NoticeRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/service/NoticeService.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/validation/ExistNotice.java
  src/main/java/com/bbteam/budgetbuddies/domain/notice/validation/NoticeExistValidation.java
  src/test/java/com/bbteam/budgetbuddies/domain/notice/service/NoticeServiceTest.java
Labels: :gear: feature

#195 [fix] EntityManager 생성 에러 해결
  src/main/java/com/bbteam/budgetbuddies/domain/notice/entity/Notice.java
Labels: :hammer_and_wrench: fix

#193 [refactor] 할인정보/지원정보 CRUD에 해시태그 엔티티 연동 및 해시태그 CRUD API 구현
  src/main/java/com/bbteam/budgetbuddies/domain/connectedinfo/repository/ConnectedInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/converter/DiscountInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/controller/HashtagApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/controller/HashtagController.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/converter/HashtagConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/dto/HashtagRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/dto/HashtagResponse.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/entity/Hashtag.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/service/HashtagService.java
  src/main/java/com/bbteam/budgetbuddies/domain/hashtag/service/HashtagServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceTest.java
Labels: :gear: feature, :test_tube: test, :recycle: refactor

#201 [feat] 지원정보 및 할인정보 북마크(좋아요한 목록) 가져오기 API 구현
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/converter/DiscountInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfolike/repository/DiscountInfoLikeRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfolike/repository/SupportInfoLikeRepository.java
Labels: :gear: feature
