Repository BudgetBuddiesTeam/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#3 [feat] Entity 클래스 생성 및 프로젝트 구조 설정
  build.gradle
  src/main/java/com/bbteam/budgetbuddies/BudgetbuddiesApplication.java
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/entity/Comment.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfolike/entity/DiscountInfoLike.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/entity/Expense.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfolike/entity/SupportInfoLike.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/entity/User.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/usercategory/entity/UserCategory.java
  src/main/java/com/bbteam/budgetbuddies/enums/Gender.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: :gear: feature

#5 [feat] Swagger 연동
  build.gradle
  src/main/java/com/bbteam/budgetbuddies/global/config/SwaggerConfig.java
Labels: :gear: feature

#8 [fix] UserCategory 삭제 및 User와 Category 연관관계 설정
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/usercategory/entity/UserCategory.java
Labels: :hammer_and_wrench: fix

#12 [feat] 할인정보 API 구현
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/converter/DiscountInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfolike/repository/DiscountInfoLikeRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/repository/UserRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/repository/package-info.java
  src/test/java/com/bbteam/budgetbuddies/domain/user/repository/UserRepositoryTest.java
Labels: :gear: feature

#20 [feat] 지원 정보 API 구현
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfolike/repository/SupportInfoLikeRepository.java
Labels: :gear: feature

#16 [feat] 사용자의 개인 카테고리 추가 API 구현
  src/main/java/com/bbteam/budgetbuddies/apiPayload/ApiResponse.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/BaseCode.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/BaseErrorCode.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/converter/CategoryConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryRequestDTO.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryResponseDTO.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentResponseDto.java
Labels: :gear: feature

#23 Update README.md
  README.md
Labels: :scroll: docs

#22 [Feat] 댓글 API 구현
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/converter/CommentConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/entity/Comment.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/repository/CommentRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/package-info.java
  src/test/java/com/bbteam/budgetbuddies/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceTest.java
Labels: :gear: feature

#24 [feat] 월별 소비 목표 조회 API 구현하기
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseListDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/package-info.java
  src/test/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :gear: feature, :test_tube: test

#27 Fix/#26
  .gitignore
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/resources/application.yaml
Labels: :hammer_and_wrench: fix, :guitar: chore

#29 [Feat] 주머니 캘린더 API 구현
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/controller/CalendarController.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/converter/CalendarConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/dto/CalendarDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/service/CalendarService.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/service/CalendarServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepository.java
  src/test/java/com/bbteam/budgetbuddies/domain/calendar/service/CalendarServiceTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepositoryTest.java
Labels: :gear: feature

#18 [feat] 또래들이 가장 큰 계획을 세운 카테고리 조회 API
  .gitignore
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/TopCategoryConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/TopGoalCategoryResponseDTO.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/repository/UserRepository.java
Labels: :gear: feature

#31 [feat] 또래나이와 성별 조회 API
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/PeerInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/PeerInfoResponseDTO.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
Labels: :gear: feature

#40 [feat] 소비 내역 추가 API
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/package-info.java
Labels: :gear: feature

#37 [feat] 댓글 Paging기능 추가
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/converter/CommentConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/entity/Comment.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/repository/CommentRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/test/java/com/bbteam/budgetbuddies/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceTest.java
Labels: :gear: feature, :recycle: refactor

#43 [Feat] CI/CD
  .github/workflows/gradle.yml
  build.gradle
Labels: :gear: feature

#41 [test] 할인정보 API 테스트 코드 작성
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfolike/entity/DiscountInfoLike.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceTest.java
Labels: :gear: feature, :test_tube: test, :recycle: refactor

#44 [Feat] 메인 화면(페이지) API 추가
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/converter/CalendarConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/dto/CalendarDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/controller/MainPageApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/controller/MainPageController.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/converter/MainPageConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/service/MainPageService.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/service/MainPageServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepository.java
Labels: :gear: feature, :recycle: refactor

#46 [feat] 유저 별 카테고리 조회 API
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
Labels: :gear: feature

#34 [feat] 메인 페이지 월 소비 분석 api 구현
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/entity/Comment.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionAnalysisConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionAnalysisResponseDTO.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
Labels: :gear: feature

#48 [test] ConsumptionGoal 테스트 코드 작성
  .gitignore
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepositoryTest.java
Labels: :test_tube: test

#50 [test] 지원정보 API 테스트 코드 작성
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfolike/entity/SupportInfoLike.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceTest.java
Labels: :test_tube: test, :hammer_and_wrench: fix, :recycle: refactor

#52 [refactor] 즉시 로딩을 지연 로딩으로 변경
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfolike/entity/DiscountInfoLike.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/entity/Expense.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfolike/entity/SupportInfoLike.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepositoryTest.java
Labels: :test_tube: test, :recycle: refactor

#53 [refactor] 할인정보와 지원정보 컨트롤러 스웨거 인터페이스로 분리
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
Labels: :recycle: refactor

#62 [chore] 소비 추가하기 관련 구조 수정
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :guitar: chore

#57 [refactor] ConsumptionGoalServiceImpl checkPeerInfo 수정
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor
