Repository BudgetBuddiesTeam/BackEnd, pull requests merged in 2024-10, with the labels that each got.

#203 [feat] 소비 분석에 따른 6가지 표정 변화 API /비교 분석 레포트 AI 멘트 구현
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumeAmountAndGoalAmountDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/MonthReportResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/controller/GeminiController.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/dto/ChatRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/dto/ChatResponse.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/service/GeminiService.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/service/GeminiServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/openai/controller/OpenAiController.java
  src/main/java/com/bbteam/budgetbuddies/domain/openai/dto/ChatGPTRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/openai/dto/ChatGPTResponse.java
  src/main/java/com/bbteam/budgetbuddies/domain/openai/dto/Message.java
  src/main/java/com/bbteam/budgetbuddies/domain/openai/service/OpenAiService.java
  src/main/java/com/bbteam/budgetbuddies/global/config/GeminiRestTemplateConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/config/OpenAiConfig.java
Labels: :gear: feature

#204 [Feat] 사용자 신고하기 구현
  src/main/java/com/bbteam/budgetbuddies/domain/report/controller/ReportApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/controller/ReportController.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/convertor/ReportConvertor.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/dto/request/ReportRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/dto/response/ReportResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/entity/Report.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/repository/ReportRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/service/ReportService.java
  src/main/java/com/bbteam/budgetbuddies/domain/report/service/ReportServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/report/repository/ReportRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/report/service/ReportServiceImplTest.java
Labels: :scroll: docs, :gear: feature, :test_tube: test, :recycle: refactor

#207 [feat] 사용자 인증 구현
  build.gradle
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/entity/User.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/repository/UserRepository.java
  src/main/java/com/bbteam/budgetbuddies/global/config/SecurityConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/controller/AuthenticationApi.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/controller/AuthenticationController.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/dto/AuthenticationRequest.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/dto/AuthenticationResponse.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/service/AuthenticationService.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/validation/PhoneNumberValidation.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/validation/ValidPhoneNumber.java
  src/main/java/com/bbteam/budgetbuddies/global/security/jwt/JwtExceptionFilter.java
  src/main/java/com/bbteam/budgetbuddies/global/security/jwt/JwtRequestFilter.java
  src/main/java/com/bbteam/budgetbuddies/global/security/jwt/JwtUtil.java
  src/main/java/com/bbteam/budgetbuddies/global/security/otp/OtpNumber.java
  src/main/java/com/bbteam/budgetbuddies/global/security/otp/OtpService.java
  src/main/java/com/bbteam/budgetbuddies/global/security/refreshtoken/RefreshToken.java
  src/main/java/com/bbteam/budgetbuddies/global/security/refreshtoken/RefreshTokenRepository.java
  src/main/java/com/bbteam/budgetbuddies/global/security/refreshtoken/RefreshTokenService.java
  src/main/java/com/bbteam/budgetbuddies/global/security/utils/CustomAuthenticationToken.java
  src/main/java/com/bbteam/budgetbuddies/global/security/utils/MyUserDetailsService.java
  src/main/java/com/bbteam/budgetbuddies/global/security/utils/PhoneNumberAuthenticationProvider.java
Labels: :gear: feature

#212 [refactor] apiPayload repository 정리
  src/main/java/com/bbteam/budgetbuddies/apiPayload/ApiResponse.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/BaseCode.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/ReasonDto.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/CommonErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/converter/UserConverter.java
Labels: :hammer_and_wrench: fix, :recycle: refactor

#210 [refactor] OtpService 메시지 전송 메소드 주석 해제
  src/main/java/com/bbteam/budgetbuddies/global/security/otp/OtpService.java
Labels: :recycle: refactor

#217 [refactor] ArgumentResolver 도입
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/UserDto.java
  src/main/java/com/bbteam/budgetbuddies/global/config/WebConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/security/otp/OtpService.java
  src/main/java/com/bbteam/budgetbuddies/global/security/utils/AuthArgumentResolver.java
  src/main/java/com/bbteam/budgetbuddies/global/security/utils/AuthUser.java
Labels: :gear: feature, :recycle: refactor
