Repository BudgetBuddiesTeam/BackEnd, pull requests merged in 2024-11, with the labels that each got.

#222 [feat] FAQ 검색기능 추가
  build.gradle
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/controller/FaqApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/controller/FaqController.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/repository/FaqRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/repository/FaqSearchRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/repository/FaqSearchRepositoryImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/service/FaqService.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/service/FaqServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/faqkeyword/domain/FaqKeyword.java
  src/main/java/com/bbteam/budgetbuddies/domain/faqkeyword/dto/FaqKeywordResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/faqkeyword/repository/FaqKeywordRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/searchkeyword/controller/SearchKeywordController.java
  src/main/java/com/bbteam/budgetbuddies/domain/searchkeyword/domain/SearchKeyword.java
  src/main/java/com/bbteam/budgetbuddies/domain/searchkeyword/repository/SearchKeywordRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/searchkeyword/service/SearchKeywordService.java
  src/test/java/com/bbteam/budgetbuddies/domain/faq/repository/FaqRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/faq/service/FaqServiceTest.java
Labels: :gear: feature

#218 [refactor] 할인정보 및 지원정보 인증된 사용자 객체를 가져오도록 수정
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
Labels: :recycle: refactor

#224 [feat] 비교분석 AI 멘트 Async 비동기 처리 + Cache 기능 추가
  build.gradle
  src/main/java/com/bbteam/budgetbuddies/BudgetbuddiesApplication.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/controller/GeminiController.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/dto/ChatRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/dto/ChatResponse.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/service/GeminiService.java
  src/main/java/com/bbteam/budgetbuddies/domain/gemini/service/GeminiServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/entity/User.java
  src/main/java/com/bbteam/budgetbuddies/global/config/CachingConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/config/GeminiRestTemplateConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/config/SecurityConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/controller/AuthenticationController.java
  src/main/java/com/bbteam/budgetbuddies/global/security/auth/service/AuthenticationService.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
Labels: :gear: feature, :recycle: refactor

#226 [refactor] userId -> ArumentResolver로 변경
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/controller/FaqApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/faq/controller/FaqController.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/controller/MainPageApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/controller/MainPageController.java
Labels: :gear: feature
