Repository BudgetBuddiesTeam/BackEnd, pull requests merged in 2024-08, with the labels that each got.

#68 [Feat] 댓글 수정 API 추가 & CommentService 분리
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/converter/CommentConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/entity/Comment.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/AbstractCommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/DiscountCommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/SupportCommentService.java
  src/test/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceTestV2.java
Labels: :gear: feature, :recycle: refactor

#66 [feat] 할인 정보 수정/삭제 API 구현
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/converter/DiscountInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceTest.java
Labels: :gear: feature, :hammer_and_wrench: fix, :recycle: refactor

#70 [feat] 지원 정보 수정/삭제 API 구현
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceTest.java
Labels: :gear: feature, :recycle: refactor

#64 [feat] 소비 추가 -> 소비 목표 추가 로직 구현
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/UserConsumptionGoalResponse.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserService.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/package-info.java
Labels: :gear: feature

#78 [feat] 공통 API관련 로직 추가
  src/main/java/com/bbteam/budgetbuddies/apiPayload/ApiResponse.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/BaseCode.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/BaseErrorCode.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/ErrorReasonDto.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/ReasonDto.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/CommonErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/bbteam/budgetbuddies/apiPayload/exception/GeneralException.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/validation/CommentExistValidation.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/validation/ExistComment.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/validation/ExistUser.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/validation/UserExistValidation.java
Labels: :gear: feature, :recycle: refactor

#74 [feat] 소비 수정하기
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseUpdateRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/entity/Expense.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/service/MainPageServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImplTest.java
Labels: :gear: feature

#82 [Refactor] CommentController Http method 변경
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerApi.java
Labels: :recycle: refactor

#84 CI/CD 동작 기준 브랜치 dev -> main 브랜치로 변경
  .github/workflows/gradle.yml
Labels: :guitar: chore

#79 [feat] 소비 목표 조회 및 가장 큰 목표 조회 Paging 추가
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/service/MainPageServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :gear: feature, :test_tube: test

#88 [refactor] 메인화면 & 주머니 캘린더 공통 응답 변경
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/controller/CalendarApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/controller/CalendarController.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/converter/CalendarConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/dto/CalendarDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/service/CalendarServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/controller/MainPageApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/controller/MainPageController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepository.java
Labels: :gear: feature, :recycle: refactor

#91 [refactor] 할인정보 및 지원정보 컨트롤러 API 공통 스펙 적용
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
Labels: :recycle: refactor

#89 [feat] 유저가 가계부에 작성한 소비 내역을 삭제하는 API
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :gear: feature

#94 [feat] User 데이터 추가 관련 로직 추가
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/controller/CalendarController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/converter/UserConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/UserDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/package-info.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserService.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserServiceImpl.java
Labels: :gear: feature

#96 [fix] CalendarTest 수정
  src/main/java/com/bbteam/budgetbuddies/domain/calendar/controller/CalendarController.java
  src/test/java/com/bbteam/budgetbuddies/domain/calendar/service/CalendarServiceTest.java
Labels: :hammer_and_wrench: fix, :recycle: refactor

#92 [test] 소비 업데이트시 소비목표의 변경되는 소비총액 테스트
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseUpdateRequestDto.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :test_tube: test

#98 [feat] 사용자의 소비목표 조회 내림차순 및 남은 소비금액 구현
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseListDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :gear: feature

#104 [test] 소비 업데이트시 소비목표의 변경되는 소비총액 테스트
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseUpdateRequestDto.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :test_tube: test

#105 [feat] 사용자의 소비목표 조회 내림차순 및 남은 소비금액 구현
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseListDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :gear: feature

#107 Revert "[test] 소비 업데이트시 소비목표의 변경되는 소비총액 테스트"
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseUpdateRequestDto.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :hammer_and_wrench: fix

#110 [refactor] 카테고리 추가 관련 리팩토링
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryRequestDTO.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/dto/CategoryResponseDTO.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseListDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#112 [feat] User 수정 로직 추가
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/converter/UserConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/UserDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/entity/User.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserService.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserServiceImpl.java
Labels: :gear: feature

#100 [refactor] 비교 분석 레포트 api 리펙토링
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionAnalysisConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/PeerInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/TopCategoryConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/TopConsumptionConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/AllConsumptionCategoryResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/AvgConsumptionGoalDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/CategoryConsumptionCountDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionAnalysisResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/MyConsumptionGoalDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/PeerInfoResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/TopCategoryConsumptionDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/TopGoalCategoryResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/converter/MainPageConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/service/MainPageServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#114 [hotfix] ConsumptionGoal Error 핫픽스
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionAnalysisConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/PeerInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/TopCategoryConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/TopConsumptionConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/AllConsumptionCategoryResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/AvgConsumptionGoalDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/CategoryConsumptionCountDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionAnalysisResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/MyConsumptionGoalDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/PeerInfoResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/TopCategoryConsumptionDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/TopGoalCategoryResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/converter/MainPageConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/mainpage/service/MainPageServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :hammer_and_wrench: fix

#116 [fix] 이름이 동일한 Dto로 인한 스웨거 버그 수정
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/converter/CommentConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/DiscountCommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/SupportCommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/converter/DiscountInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/converter/UserConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/UserDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserService.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceTestV2.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceTest.java
Labels: :hammer_and_wrench: fix

#117 [v3] dto 이름 수정
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/converter/CommentConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/CommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/DiscountCommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/service/SupportCommentService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/converter/DiscountInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/converter/UserConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/UserDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserService.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/comment/service/CommentServiceTestV2.java
  src/test/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceTest.java
Labels: :recycle: refactor

#118 [feat] 남은 금액 필드 추가 및 남은 금액 내림차순 구현
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseListDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/CompactExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseUpdateRequestDto.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :gear: feature, :test_tube: test, :hammer_and_wrench: fix

#120 [refactor] consumptionGoal 공통 응답 추가
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
Labels: :recycle: refactor

#121 [v4] consumptionGoal 공통 응답 처리
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/converter/ConsumptionGoalConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/dto/ConsumptionGoalResponseListDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/CompactExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseUpdateRequestDto.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#123 [feat] User Api 추가
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/UserDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserService.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserServiceImpl.java
Labels: :gear: feature, :recycle: refactor

#124 [v5] UserApi 추가 및 URL 변경
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/dto/UserDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserService.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/service/UserServiceImpl.java
Labels: :gear: feature

#126 [fix] UserController URL 에러 fix
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
Labels: :hammer_and_wrench: fix

#128 [FIX] expense 조회시 카테고리도 함께 반환되도록 구현
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/CompactExpenseResponseDto.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImplTest.java
Labels: :gear: feature, :guitar: chore

#129 [FIX] expense 조회시 카테고리도 함께 반환되도록 구현
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/CompactExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/user/controller/UserController.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImplTest.java
Labels: :hammer_and_wrench: fix

#130 [feat] 카테고리 삭제 기능 구현
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/entity/Expense.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
Labels: :gear: feature

#132 [feat] 월별 소비 조회 전체 소비금액 구현 및 일별 반환 #131
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/CompactExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/MonthlyExpenseCompactResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImplTest.java
Labels: :gear: feature, :test_tube: test, :recycle: refactor, :guitar: chore

#135 [v6] 월별 소비 조회 총 소비 금액 및 요일별로 반환
  src/main/java/com/bbteam/budgetbuddies/common/BaseEntity.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/controller/CategoryController.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/entity/Category.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryService.java
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/entity/ConsumptionGoal.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/CompactExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/MonthlyExpenseCompactResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/entity/Expense.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImplTest.java
Labels: :gear: feature

#134 [refactor] consumptionGoal Controller 엔드포인트 수정
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/controller/ConsumptionGoalController.java
Labels: :recycle: refactor

#136 [fix] 카테고리 추가시의 엔티티 내용 수정
  src/main/java/com/bbteam/budgetbuddies/domain/category/converter/CategoryConverter.java
Labels: :hammer_and_wrench: fix

#143 [feat] ci/cd deploy.sh 추가
  .github/workflows/gradle.yml
Labels: :gear: feature

#144 [v7] 소비 및 카테고리 관련 로직 리팩토링 & 무중단 배포 구축
  .github/workflows/gradle.yml
  src/main/java/com/bbteam/budgetbuddies/domain/category/converter/CategoryConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/ExpenseRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :gear: feature, :recycle: refactor

#145 [feat] 월별 소비 조회 전체 소비금액 구현 및 일별 반환
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/DailyExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/MonthlyExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImplTest.java
Labels: :guitar: chore

#146 [v6.1] 월별 소비 조회 총 소비 금액 및 요일별로 반환
  src/main/java/com/bbteam/budgetbuddies/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentController.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/controller/CommentControllerApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/controller/ExpenseController.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/converter/ExpenseConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/DailyExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/dto/MonthlyExpenseResponseDto.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseService.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImplTest.java
Labels: :guitar: chore

#147 [fix] 카테고리 조회시 deleted 컬럼 반영
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
Labels: :hammer_and_wrench: fix

#149 [feat] 스웨거 보안 설정
  build.gradle
  src/main/java/com/bbteam/budgetbuddies/global/config/SecurityConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/config/SwaggerConfig.java
Labels: :gear: feature

#150 [fix] 할인정보 및 지원정보 수정/삭제 버그 수정
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
Labels: :hammer_and_wrench: fix

#151 [v7] API 버그 수정 및 스웨거 보안 설정
  build.gradle
  src/main/java/com/bbteam/budgetbuddies/domain/category/repository/CategoryRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/controller/DiscountInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/service/DiscountInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoApi.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/controller/SupportInfoController.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoService.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/service/SupportInfoServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/global/config/SecurityConfig.java
  src/main/java/com/bbteam/budgetbuddies/global/config/SwaggerConfig.java
Labels: :gear: feature, :hammer_and_wrench: fix

#152 [fix] 카테고리 추가시 consumptionGoal의 delete flag에 관한 버그 수정
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :hammer_and_wrench: fix

#154 [fix] SecurityConfig csrf 설정 비활성화 (HOTFIX)
  src/main/java/com/bbteam/budgetbuddies/global/config/SecurityConfig.java
Labels: :hammer_and_wrench: fix

#155 [v8] 카테고리 추가시 consumptionGoal의 delete flag에 관한 버그 수정
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :hammer_and_wrench: fix

#157 [feat] Calendar 관련 DiscountInfo, SupportInfo field 추가
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/converter/DiscountInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/dto/DiscountRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/entity/DiscountInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/discountinfo/repository/DiscountInfoRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/converter/SupportInfoConverter.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/dto/SupportRequest.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/entity/SupportInfo.java
  src/main/java/com/bbteam/budgetbuddies/domain/supportinfo/repository/SupportInfoRepository.java
Labels: :gear: feature

#161 [refactor] 소비 건수 오류 수정
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/global/config/SecurityConfig.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#165 [fix] 과거 소비, 카테고리, 소비 목표에 대한 반영 건의 오류 수정
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :hammer_and_wrench: fix

#167 [refactor] 소비 레포트 소비 top3 조회 수정
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#169 [refactor] 소비 레포트 소비 조회 수정
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#166 [v11] 가계부 소비, 카테고리 삭제 관련 버그 수정
  src/main/java/com/bbteam/budgetbuddies/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalService.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :hammer_and_wrench: fix

#170 [chore] main과 dev 브랜치 맞추기
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :guitar: chore

#171 [refactor] 소비 레포트 소비 건 조회 consumptionGoal -> expense로 변경
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#172 [v12] 소비 레포트 top 소비 조회 변경
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepository.java
  src/main/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceImpl.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/repository/ConsumptionGoalRepositoryTest.java
  src/test/java/com/bbteam/budgetbuddies/domain/consumptiongoal/service/ConsumptionGoalServiceTest.java
Labels: :recycle: refactor

#178 [Hotfix] expense 말일 조회되도록 수정
  src/main/java/com/bbteam/budgetbuddies/domain/expense/service/ExpenseServiceImpl.java
Labels: :hammer_and_wrench: fix
